# employee_gui.py
# France Cheong
# 22/11/2018

# ########
# Packages
# ########
import tkinter as tk
from tkinter import messagebox
import tkinter.ttk as ttk # for combobox

from database import getSession
from movie_dao import MovieDAO# To communicate with Employee table
from movie_validation import Validation # To validate the entries made on the form

# #################
# MovieGUI Class
# #################
getSession = getSession()
class MovieGUI():

    def __init__(self):   
      
        self.movie_dao = MovieDAO()

        self.validator = Validation()

        self.movie_id = tk.StringVar()
        self.movie_name = tk.StringVar()
        self.ratings = tk.StringVar()

        self.lb_ids = None

        self.mb_title_bar = "Movie CRUD"

        pass 

    def create_gui(self, root):
     
        print("Creating movie GUI ...")


        movie_frame = tk.Frame(root)
        movie_frame.pack()

        form_frame = tk.Frame(movie_frame)
        form_frame.pack()
    
        tk.Label(form_frame, font=('arial', 10), 
                 text = "Movie ID").grid(row=0, column=0, columnspan=3)

        tk.Label(form_frame, text= "Movie ID", font=('arial', 10), width=20, 
                 anchor="e", bd=1, pady=10, padx=10).grid(row=1, column=0)
        tk.Entry(form_frame, textvariable=self.movie_id, width=30, bd=1, 
                 state=tk.DISABLED).grid(row=1, column=1)

        # row 2: firstname label, firstname entry and listbox of ids
        tk.Label(form_frame, text= "Movie name", font=('arial', 10), 
                 width=20, anchor="e", bd=1, pady=10, padx=10).grid(row=2, column=0)
        tk.Entry(form_frame, textvariable=self.movie_name, 
                 width=30, bd=1).grid(row=2, column=1)
        
        self.lb_ids = tk.Listbox(form_frame)
        self.lb_ids.grid(row=2, column=4, rowspan=5) 

        self.lb_ids.bind('<<ListboxSelect>>', self.on_list_select)
        # row 3: lastname label and entry (the listbox will go through)
        tk.Label(form_frame, text= "Ratings", font=('arial', 10), width=20, 
                 anchor="e", bd=1, pady=10, padx=10).grid(row=3, column=0)
        tk.Entry(form_frame, textvariable=self.ratings, 
                 width=30, bd=1).grid(row=3, column=1)

       
        button_frame = tk.Frame(movie_frame, pady=10) 
        button_frame.pack()
   
        tk.Button(button_frame, width=10, text="Clear", 
                  command=self.clear_fields).pack(side=tk.LEFT)
        tk.Button(button_frame, width=10, text="Save", 
                  command=self.save).pack(side=tk.LEFT)
        tk.Button(button_frame, width=10, text="Delete", 
                  command=self.delete).pack(side=tk.LEFT)
        tk.Button(button_frame, width=10, text="Load", 
                  command=self.load).pack(side=tk.LEFT)       

        return movie_frame

    def clear_fields(self):

        # Just blank all the fields
        self.movie_id.set("")
        self.movie_name.set("")
        self.ratings.set("")
        pass

    def save(self):
       
        print("Saving a movie ...")

        # Get the data
        data = self.get_fields()   

        # Validate the data
        valid_data, message = self.validate_fields(data)
        if valid_data:
            if (len(data['movie_id'])==0):
                # If nothing has been entered in employee_id 
                # i.e. its length is zero characters
                print("Calling create() as customer_id is absent")
                self.create(data)
            else:
                print("Calling update() as customer_id is present")
                self.update(data)
                pass
        else:
            message_text = "Invalid fields.\n" + message 
            messagebox.showwarning(self.mb_title_bar, message_text, icon="warning")
            pass

    def get_fields(self):


        movie = {}
        # employee_id is ignored when creating a record
        movie['movie_id'] = self.movie_id.get() 
        movie['movie_name'] = self.movie_name.get()
        movie['ratings'] = self.ratings.get()
        return movie

    def validate_fields(self, data):
      
           
        # By default set to true, anything wrong will turn it to false   
        valid_data = True 
        # Instantiate an empty list to contain the messages
        message_list = [] 
        # Check for blank fields
        # Do not check employee_id as this is generated by the database
        #if len(data['employee_id']==0:
        #    valid_data = False
        #    message_list.append("employee_id is empty")
        if len(data['movie_name'])==0:
            valid_data = False
            message_list.append("movie_name is empty")
        if len(data['ratings'])==0:
            valid_data = False
            message_list.append("ratings is empty")
 
        # Other possible checks

        # Implement these as functions in the Validation class so that 
        # other classes can call them
         
        # Check if firstname and lastname contain  
        # only alphabetic characters (and may be certain special characters)
        if not self.validator.is_not_symbol(data['movie_name']):
            valid_data = False
            message_list.append("invalid movie name")

        if not self.validator.is_symbol(data['ratings']):
            valid_data = False
            message_list.append("invalid ratings")
    
      
            
        # Join the items in the list as a string separated with a comma and a space    
        message = ', '.join(message_list) 

        return valid_data, message # return 2 values

    def create(self, data):
       

        print("Creating an customer ...")
        print(data)

        session = getSession.get_db_session() # Get a session (database.py)
        result = self.movie_dao.create(session, data) 
    
        session.close() # Close the session

        messagebox.showinfo(self.mb_title_bar, result)
 
        pass

    def update(self, data):

        print("Updating an employee ...")
        print(data)

        session = getSession.get_db_session() # Get a session (database.py)
        result = self.movie_dao.update(session, data['movie_id'], data)
        session.close() # close the session

        messagebox.showinfo(self.mb_title_bar, result)
        pass

    def delete(self):

        print("Deleting a movie ...")
        movie_id = self.movie_id.get() 
        print(movie_id)
        
        # Call the data access object to do the job
        # Pass the id as parameter to the delete() method
        session = getSession.get_db_session() # Get a session (database.py)
        result = self.movie_dao.delete(session, movie_id)
        session.close() # Close the session

        # Display the returned message to the user - use a messagebox    
        # Display everything that is returned in the result    
        messagebox.showinfo(self.mb_title_bar, result)
        pass
        pass
    def load(self):
       
        session = getSession.get_db_session() # Get a session (database.py)
        result = self.movie_dao.find_ids(session) # {"employee_ids": [1, 2, 3]}
        session.close() # Close the session
        print("result", result)
        # Check if there is an entry in the result dictionary
        
        if "movie_ids" in result: 
            list_ids = result['movie_ids'] # will crash if there is no entry!
            # Set the returned list into the listbox
            # Before doing that, must clear any previous list in the box
            self.lb_ids.delete(0,tk.END)
            print("Setting movie_id in listbox ...")
            for x in list_ids:
                self.lb_ids.insert(tk.END, x)
                #print(x)
            pass

    def on_list_select(self, evt):
       
        # For more information on 'tkinter events', 
        # refer to http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm
        w = evt.widget
        index = int(w.curselection()[0]) 
          # index = position of the item clicked in the list, first item is item 0 not 1
        value = w.get(index) 
          # value of the item clicked, in our case it's the employee_id
        print(index) 
        print(value)

        # Call find_by_id and populate the stringvars of the form
        session = getSession.get_db_session() # Get a session (database.py)
        result = self.movie_dao.find_by_id(session, value)   
        session.close() # close the session
        print("result", result) 
           # { "employee" : {"employee_id": "", "firstname": "", etc}}
        movie = result['movie']
        self.populate_fields(movie)
        pass

    def populate_fields(self, movie):
       

        # Set the values from the dict to the stringvars
        self.movie_id.set(movie['movie_id'])
        self.movie_name.set(movie['movie_name'])
        self.ratings.set(movie['ratings'])
        pass

# ###########
# Main method
# ###########

    def main(self):
        """
        The main method is only executed when the file is 'run' 
        (not imported in another file)
        """
        
        # Setup a root window (in the middle of the screen)
        root = tk.Tk()
        root.title("Procurement System")
        screen_width = root.winfo_screenwidth()
        screen_height = root.winfo_screenheight()
        width = 900
        height = 500
        x = (screen_width/2) - (width/2)
        y = (screen_height/2) - (height/2)
        root.geometry('%dx%d+%d+%d' % (width, height, x, y))
        root.resizable(0, 0)

        # Instantiate the gui
        gui = MovieGUI()

        # Create the gui
        # pass the root window as parameter
        gui.create_gui(root)

        # Run the mainloop 
        # the endless window loop to process user inputs
        root.mainloop()
        pass